// Generated by gencpp from file pxpincher_msgs/RelaxResponse.msg
// DO NOT EDIT!


#ifndef PXPINCHER_MSGS_MESSAGE_RELAXRESPONSE_H
#define PXPINCHER_MSGS_MESSAGE_RELAXRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pxpincher_msgs
{
template <class ContainerAllocator>
struct RelaxResponse_
{
  typedef RelaxResponse_<ContainerAllocator> Type;

  RelaxResponse_()
    : success(false)  {
    }
  RelaxResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RelaxResponse_

typedef ::pxpincher_msgs::RelaxResponse_<std::allocator<void> > RelaxResponse;

typedef boost::shared_ptr< ::pxpincher_msgs::RelaxResponse > RelaxResponsePtr;
typedef boost::shared_ptr< ::pxpincher_msgs::RelaxResponse const> RelaxResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pxpincher_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pxpincher_msgs': ['/home/turtlebot/catkin_ws/src/pxpincher_ros/pxpincher_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::pxpincher_msgs::RelaxResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pxpincher_msgs/RelaxResponse";
  }

  static const char* value(const ::pxpincher_msgs::RelaxResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const ::pxpincher_msgs::RelaxResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelaxResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pxpincher_msgs::RelaxResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pxpincher_msgs::RelaxResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PXPINCHER_MSGS_MESSAGE_RELAXRESPONSE_H
