// Generated by gencpp from file pxpincher_msgs/Relax.msg
// DO NOT EDIT!


#ifndef PXPINCHER_MSGS_MESSAGE_RELAX_H
#define PXPINCHER_MSGS_MESSAGE_RELAX_H

#include <ros/service_traits.h>


#include <pxpincher_msgs/RelaxRequest.h>
#include <pxpincher_msgs/RelaxResponse.h>


namespace pxpincher_msgs
{

struct Relax
{

typedef RelaxRequest Request;
typedef RelaxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Relax
} // namespace pxpincher_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pxpincher_msgs::Relax > {
  static const char* value()
  {
    return "f9c9ebe1661ef5f1f7049e7ba4c3d341";
  }

  static const char* value(const ::pxpincher_msgs::Relax&) { return value(); }
};

template<>
struct DataType< ::pxpincher_msgs::Relax > {
  static const char* value()
  {
    return "pxpincher_msgs/Relax";
  }

  static const char* value(const ::pxpincher_msgs::Relax&) { return value(); }
};


// service_traits::MD5Sum< ::pxpincher_msgs::RelaxRequest> should match 
// service_traits::MD5Sum< ::pxpincher_msgs::Relax > 
template<>
struct MD5Sum< ::pxpincher_msgs::RelaxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pxpincher_msgs::Relax >::value();
  }
  static const char* value(const ::pxpincher_msgs::RelaxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pxpincher_msgs::RelaxRequest> should match 
// service_traits::DataType< ::pxpincher_msgs::Relax > 
template<>
struct DataType< ::pxpincher_msgs::RelaxRequest>
{
  static const char* value()
  {
    return DataType< ::pxpincher_msgs::Relax >::value();
  }
  static const char* value(const ::pxpincher_msgs::RelaxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pxpincher_msgs::RelaxResponse> should match 
// service_traits::MD5Sum< ::pxpincher_msgs::Relax > 
template<>
struct MD5Sum< ::pxpincher_msgs::RelaxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pxpincher_msgs::Relax >::value();
  }
  static const char* value(const ::pxpincher_msgs::RelaxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pxpincher_msgs::RelaxResponse> should match 
// service_traits::DataType< ::pxpincher_msgs::Relax > 
template<>
struct DataType< ::pxpincher_msgs::RelaxResponse>
{
  static const char* value()
  {
    return DataType< ::pxpincher_msgs::Relax >::value();
  }
  static const char* value(const ::pxpincher_msgs::RelaxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PXPINCHER_MSGS_MESSAGE_RELAX_H
